language: java
jdk:
  - openjdk8

jobs:
  include:
    - stage: unit-test
      script: echo 'unit test'
    - stage: integration-test
      script: echo 'integration test'
    - stage: deploy
      script: echo 'deploy'

stages:
  - unit-test
  - name: integration-test
    if: branch = master
  - name: deploy
    if: branch = master

#install: mvn install
#before_script:
#script:
#after_script:
#deploy:
#after_deploy: