name: My Demo Index
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo '🎉 hello gh actions.'
  say-java-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: java -version
      - run: mvn --version
  say-goodbay:
    runs-on: ubuntu-latest
    steps:
      - run: echo '👾 goodbye gh actions.'
